//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  prices: Prices;
  pricesConnection: PricesConnection;
  contacts: Contacts;
  contactsConnection: ContactsConnection;
  about: About;
  aboutConnection: AboutConnection;
  services: Services;
  servicesConnection: ServicesConnection;
  groups: Groups;
  groupsConnection: GroupsConnection;
  documents: Documents;
  documentsConnection: DocumentsConnection;
  team: Team;
  teamConnection: TeamConnection;
  promo: Promo;
  promoConnection: PromoConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryPricesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPricesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PricesFilter>;
};


export type QueryContactsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactsFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryServicesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
};


export type QueryGroupsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGroupsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GroupsFilter>;
};


export type QueryDocumentsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentsFilter>;
};


export type QueryTeamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
};


export type QueryPromoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPromoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PromoFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  prices?: InputMaybe<PricesFilter>;
  contacts?: InputMaybe<ContactsFilter>;
  about?: InputMaybe<AboutFilter>;
  services?: InputMaybe<ServicesFilter>;
  groups?: InputMaybe<GroupsFilter>;
  documents?: InputMaybe<DocumentsFilter>;
  team?: InputMaybe<TeamFilter>;
  promo?: InputMaybe<PromoFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Prices | Contacts | About | Services | Groups | Documents | Team | Promo | Folder;

export type HomeHero = {
  __typename?: 'HomeHero';
  badge?: Maybe<Scalars['String']['output']>;
  title_main?: Maybe<Scalars['String']['output']>;
  title_gradient?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  cta_primary?: Maybe<Scalars['String']['output']>;
  cta_secondary?: Maybe<Scalars['String']['output']>;
};

export type HomeAdvantagesItems = {
  __typename?: 'HomeAdvantagesItems';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type HomeAdvantages = {
  __typename?: 'HomeAdvantages';
  title_main?: Maybe<Scalars['String']['output']>;
  title_gradient?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<HomeAdvantagesItems>>>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  hero?: Maybe<HomeHero>;
  advantages?: Maybe<HomeAdvantages>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  title_main?: InputMaybe<StringFilter>;
  title_gradient?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  cta_primary?: InputMaybe<StringFilter>;
  cta_secondary?: InputMaybe<StringFilter>;
};

export type HomeAdvantagesItemsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type HomeAdvantagesFilter = {
  title_main?: InputMaybe<StringFilter>;
  title_gradient?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  items?: InputMaybe<HomeAdvantagesItemsFilter>;
};

export type HomeFilter = {
  hero?: InputMaybe<HomeHeroFilter>;
  advantages?: InputMaybe<HomeAdvantagesFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type PricesHero = {
  __typename?: 'PricesHero';
  badge?: Maybe<Scalars['String']['output']>;
  title_main?: Maybe<Scalars['String']['output']>;
  title_gradient?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type PricesPlansFeatures = {
  __typename?: 'PricesPlansFeatures';
  text?: Maybe<Scalars['String']['output']>;
  included?: Maybe<Scalars['Boolean']['output']>;
};

export type PricesPlans = {
  __typename?: 'PricesPlans';
  id?: Maybe<Scalars['String']['output']>;
  emoji?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  time?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  unit?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  featured_badge?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<PricesPlansFeatures>>>;
};

export type PricesInfoItems = {
  __typename?: 'PricesInfoItems';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type PricesInfo = {
  __typename?: 'PricesInfo';
  title?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<PricesInfoItems>>>;
};

export type Prices = Node & Document & {
  __typename?: 'Prices';
  hero?: Maybe<PricesHero>;
  plans?: Maybe<Array<Maybe<PricesPlans>>>;
  info?: Maybe<PricesInfo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PricesHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  title_main?: InputMaybe<StringFilter>;
  title_gradient?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PricesPlansFeaturesFilter = {
  text?: InputMaybe<StringFilter>;
  included?: InputMaybe<BooleanFilter>;
};

export type PricesPlansFilter = {
  id?: InputMaybe<StringFilter>;
  emoji?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  time?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  unit?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  featured_badge?: InputMaybe<StringFilter>;
  features?: InputMaybe<PricesPlansFeaturesFilter>;
};

export type PricesInfoItemsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type PricesInfoFilter = {
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<PricesInfoItemsFilter>;
};

export type PricesFilter = {
  hero?: InputMaybe<PricesHeroFilter>;
  plans?: InputMaybe<PricesPlansFilter>;
  info?: InputMaybe<PricesInfoFilter>;
};

export type PricesConnectionEdges = {
  __typename?: 'PricesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Prices>;
};

export type PricesConnection = Connection & {
  __typename?: 'PricesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PricesConnectionEdges>>>;
};

export type ContactsHero = {
  __typename?: 'ContactsHero';
  badge?: Maybe<Scalars['String']['output']>;
  title_main?: Maybe<Scalars['String']['output']>;
  title_gradient?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type ContactsContacts = {
  __typename?: 'ContactsContacts';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
  link_text?: Maybe<Scalars['String']['output']>;
  note?: Maybe<Scalars['String']['output']>;
  multiline_text?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ContactsMap = {
  __typename?: 'ContactsMap';
  url?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
};

export type Contacts = Node & Document & {
  __typename?: 'Contacts';
  hero?: Maybe<ContactsHero>;
  contacts?: Maybe<Array<Maybe<ContactsContacts>>>;
  map?: Maybe<ContactsMap>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactsHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  title_main?: InputMaybe<StringFilter>;
  title_gradient?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type ContactsContactsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
  link_text?: InputMaybe<StringFilter>;
  note?: InputMaybe<StringFilter>;
  multiline_text?: InputMaybe<StringFilter>;
};

export type ContactsMapFilter = {
  url?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type ContactsFilter = {
  hero?: InputMaybe<ContactsHeroFilter>;
  contacts?: InputMaybe<ContactsContactsFilter>;
  map?: InputMaybe<ContactsMapFilter>;
};

export type ContactsConnectionEdges = {
  __typename?: 'ContactsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contacts>;
};

export type ContactsConnection = Connection & {
  __typename?: 'ContactsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactsConnectionEdges>>>;
};

export type AboutHero = {
  __typename?: 'AboutHero';
  badge?: Maybe<Scalars['String']['output']>;
  title_main?: Maybe<Scalars['String']['output']>;
  title_gradient?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type AboutMission = {
  __typename?: 'AboutMission';
  title?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  visual_label?: Maybe<Scalars['String']['output']>;
  visual_emoji?: Maybe<Scalars['String']['output']>;
};

export type AboutValuesItems = {
  __typename?: 'AboutValuesItems';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type AboutValues = {
  __typename?: 'AboutValues';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<AboutValuesItems>>>;
};

export type AboutEnvironment = {
  __typename?: 'AboutEnvironment';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type About = Node & Document & {
  __typename?: 'About';
  hero?: Maybe<AboutHero>;
  mission?: Maybe<AboutMission>;
  values?: Maybe<AboutValues>;
  environment?: Maybe<AboutEnvironment>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  title_main?: InputMaybe<StringFilter>;
  title_gradient?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type AboutMissionFilter = {
  title?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<StringFilter>;
  visual_label?: InputMaybe<StringFilter>;
  visual_emoji?: InputMaybe<StringFilter>;
};

export type AboutValuesItemsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type AboutValuesFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  items?: InputMaybe<AboutValuesItemsFilter>;
};

export type AboutEnvironmentFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
};

export type AboutFilter = {
  hero?: InputMaybe<AboutHeroFilter>;
  mission?: InputMaybe<AboutMissionFilter>;
  values?: InputMaybe<AboutValuesFilter>;
  environment?: InputMaybe<AboutEnvironmentFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type ServicesHero = {
  __typename?: 'ServicesHero';
  badge?: Maybe<Scalars['String']['output']>;
  title_main?: Maybe<Scalars['String']['output']>;
  title_gradient?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type ServicesServicesPrices = {
  __typename?: 'ServicesServicesPrices';
  name?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
};

export type ServicesServices = {
  __typename?: 'ServicesServices';
  id?: Maybe<Scalars['String']['output']>;
  emoji?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  features_title?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  pricing_title?: Maybe<Scalars['String']['output']>;
  prices?: Maybe<Array<Maybe<ServicesServicesPrices>>>;
};

export type ServicesCta = {
  __typename?: 'ServicesCta';
  title_main?: Maybe<Scalars['String']['output']>;
  title_gradient?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  phone_text?: Maybe<Scalars['String']['output']>;
  email_text?: Maybe<Scalars['String']['output']>;
};

export type Services = Node & Document & {
  __typename?: 'Services';
  hero?: Maybe<ServicesHero>;
  services?: Maybe<Array<Maybe<ServicesServices>>>;
  cta?: Maybe<ServicesCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServicesHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  title_main?: InputMaybe<StringFilter>;
  title_gradient?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type ServicesServicesPricesFilter = {
  name?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
};

export type ServicesServicesFilter = {
  id?: InputMaybe<StringFilter>;
  emoji?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  features_title?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
  pricing_title?: InputMaybe<StringFilter>;
  prices?: InputMaybe<ServicesServicesPricesFilter>;
};

export type ServicesCtaFilter = {
  title_main?: InputMaybe<StringFilter>;
  title_gradient?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  phone_text?: InputMaybe<StringFilter>;
  email_text?: InputMaybe<StringFilter>;
};

export type ServicesFilter = {
  hero?: InputMaybe<ServicesHeroFilter>;
  services?: InputMaybe<ServicesServicesFilter>;
  cta?: InputMaybe<ServicesCtaFilter>;
};

export type ServicesConnectionEdges = {
  __typename?: 'ServicesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services>;
};

export type ServicesConnection = Connection & {
  __typename?: 'ServicesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServicesConnectionEdges>>>;
};

export type GroupsHero = {
  __typename?: 'GroupsHero';
  badge?: Maybe<Scalars['String']['output']>;
  title_main?: Maybe<Scalars['String']['output']>;
  title_gradient?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type GroupsItems = {
  __typename?: 'GroupsItems';
  id?: Maybe<Scalars['String']['output']>;
  emoji?: Maybe<Scalars['String']['output']>;
  age?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
  features_title?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  cta?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
};

export type Groups = Node & Document & {
  __typename?: 'Groups';
  hero?: Maybe<GroupsHero>;
  items?: Maybe<Array<Maybe<GroupsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GroupsHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  title_main?: InputMaybe<StringFilter>;
  title_gradient?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type GroupsItemsFilter = {
  id?: InputMaybe<StringFilter>;
  emoji?: InputMaybe<StringFilter>;
  age?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
  features_title?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type GroupsFilter = {
  hero?: InputMaybe<GroupsHeroFilter>;
  items?: InputMaybe<GroupsItemsFilter>;
};

export type GroupsConnectionEdges = {
  __typename?: 'GroupsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Groups>;
};

export type GroupsConnection = Connection & {
  __typename?: 'GroupsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GroupsConnectionEdges>>>;
};

export type DocumentsHero = {
  __typename?: 'DocumentsHero';
  badge?: Maybe<Scalars['String']['output']>;
  title_main?: Maybe<Scalars['String']['output']>;
  title_gradient?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type DocumentsCategories = {
  __typename?: 'DocumentsCategories';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Documents = Node & Document & {
  __typename?: 'Documents';
  hero?: Maybe<DocumentsHero>;
  categories?: Maybe<Array<Maybe<DocumentsCategories>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DocumentsHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  title_main?: InputMaybe<StringFilter>;
  title_gradient?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type DocumentsCategoriesFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  items?: InputMaybe<StringFilter>;
};

export type DocumentsFilter = {
  hero?: InputMaybe<DocumentsHeroFilter>;
  categories?: InputMaybe<DocumentsCategoriesFilter>;
};

export type DocumentsConnectionEdges = {
  __typename?: 'DocumentsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Documents>;
};

export type DocumentsConnection = Connection & {
  __typename?: 'DocumentsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentsConnectionEdges>>>;
};

export type TeamMembers = {
  __typename?: 'TeamMembers';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  emoji?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  birthday?: Maybe<Scalars['String']['output']>;
  education?: Maybe<Scalars['String']['output']>;
  motto?: Maybe<Scalars['String']['output']>;
};

export type Team = Node & Document & {
  __typename?: 'Team';
  members?: Maybe<Array<Maybe<TeamMembers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TeamMembersFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  emoji?: InputMaybe<StringFilter>;
  photo?: InputMaybe<StringFilter>;
  birthday?: InputMaybe<StringFilter>;
  education?: InputMaybe<StringFilter>;
  motto?: InputMaybe<StringFilter>;
};

export type TeamFilter = {
  members?: InputMaybe<TeamMembersFilter>;
};

export type TeamConnectionEdges = {
  __typename?: 'TeamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team>;
};

export type TeamConnection = Connection & {
  __typename?: 'TeamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamConnectionEdges>>>;
};

export type Promo = Node & Document & {
  __typename?: 'Promo';
  enabled?: Maybe<Scalars['Boolean']['output']>;
  badge?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  bannerText?: Maybe<Scalars['String']['output']>;
  buttonText?: Maybe<Scalars['String']['output']>;
  buttonLink?: Maybe<Scalars['String']['output']>;
  color?: Maybe<Scalars['String']['output']>;
  expiresAt?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PromoFilter = {
  enabled?: InputMaybe<BooleanFilter>;
  badge?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  bannerText?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  buttonLink?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
  expiresAt?: InputMaybe<StringFilter>;
};

export type PromoConnectionEdges = {
  __typename?: 'PromoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Promo>;
};

export type PromoConnection = Connection & {
  __typename?: 'PromoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PromoConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updatePrices: Prices;
  createPrices: Prices;
  updateContacts: Contacts;
  createContacts: Contacts;
  updateAbout: About;
  createAbout: About;
  updateServices: Services;
  createServices: Services;
  updateGroups: Groups;
  createGroups: Groups;
  updateDocuments: Documents;
  createDocuments: Documents;
  updateTeam: Team;
  createTeam: Team;
  updatePromo: Promo;
  createPromo: Promo;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdatePricesArgs = {
  relativePath: Scalars['String']['input'];
  params: PricesMutation;
};


export type MutationCreatePricesArgs = {
  relativePath: Scalars['String']['input'];
  params: PricesMutation;
};


export type MutationUpdateContactsArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactsMutation;
};


export type MutationCreateContactsArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactsMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationCreateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationUpdateGroupsArgs = {
  relativePath: Scalars['String']['input'];
  params: GroupsMutation;
};


export type MutationCreateGroupsArgs = {
  relativePath: Scalars['String']['input'];
  params: GroupsMutation;
};


export type MutationUpdateDocumentsArgs = {
  relativePath: Scalars['String']['input'];
  params: DocumentsMutation;
};


export type MutationCreateDocumentsArgs = {
  relativePath: Scalars['String']['input'];
  params: DocumentsMutation;
};


export type MutationUpdateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationCreateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationUpdatePromoArgs = {
  relativePath: Scalars['String']['input'];
  params: PromoMutation;
};


export type MutationCreatePromoArgs = {
  relativePath: Scalars['String']['input'];
  params: PromoMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  prices?: InputMaybe<PricesMutation>;
  contacts?: InputMaybe<ContactsMutation>;
  about?: InputMaybe<AboutMutation>;
  services?: InputMaybe<ServicesMutation>;
  groups?: InputMaybe<GroupsMutation>;
  documents?: InputMaybe<DocumentsMutation>;
  team?: InputMaybe<TeamMutation>;
  promo?: InputMaybe<PromoMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  prices?: InputMaybe<PricesMutation>;
  contacts?: InputMaybe<ContactsMutation>;
  about?: InputMaybe<AboutMutation>;
  services?: InputMaybe<ServicesMutation>;
  groups?: InputMaybe<GroupsMutation>;
  documents?: InputMaybe<DocumentsMutation>;
  team?: InputMaybe<TeamMutation>;
  promo?: InputMaybe<PromoMutation>;
};

export type HomeHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title_main?: InputMaybe<Scalars['String']['input']>;
  title_gradient?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  cta_primary?: InputMaybe<Scalars['String']['input']>;
  cta_secondary?: InputMaybe<Scalars['String']['input']>;
};

export type HomeAdvantagesItemsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type HomeAdvantagesMutation = {
  title_main?: InputMaybe<Scalars['String']['input']>;
  title_gradient?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<HomeAdvantagesItemsMutation>>>;
};

export type HomeMutation = {
  hero?: InputMaybe<HomeHeroMutation>;
  advantages?: InputMaybe<HomeAdvantagesMutation>;
};

export type PricesHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title_main?: InputMaybe<Scalars['String']['input']>;
  title_gradient?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type PricesPlansFeaturesMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  included?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PricesPlansMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  emoji?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  unit?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  featured_badge?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<PricesPlansFeaturesMutation>>>;
};

export type PricesInfoItemsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type PricesInfoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PricesInfoItemsMutation>>>;
};

export type PricesMutation = {
  hero?: InputMaybe<PricesHeroMutation>;
  plans?: InputMaybe<Array<InputMaybe<PricesPlansMutation>>>;
  info?: InputMaybe<PricesInfoMutation>;
};

export type ContactsHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title_main?: InputMaybe<Scalars['String']['input']>;
  title_gradient?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type ContactsContactsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  link_text?: InputMaybe<Scalars['String']['input']>;
  note?: InputMaybe<Scalars['String']['input']>;
  multiline_text?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ContactsMapMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
};

export type ContactsMutation = {
  hero?: InputMaybe<ContactsHeroMutation>;
  contacts?: InputMaybe<Array<InputMaybe<ContactsContactsMutation>>>;
  map?: InputMaybe<ContactsMapMutation>;
};

export type AboutHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title_main?: InputMaybe<Scalars['String']['input']>;
  title_gradient?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMissionMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  visual_label?: InputMaybe<Scalars['String']['input']>;
  visual_emoji?: InputMaybe<Scalars['String']['input']>;
};

export type AboutValuesItemsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type AboutValuesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<AboutValuesItemsMutation>>>;
};

export type AboutEnvironmentMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type AboutMutation = {
  hero?: InputMaybe<AboutHeroMutation>;
  mission?: InputMaybe<AboutMissionMutation>;
  values?: InputMaybe<AboutValuesMutation>;
  environment?: InputMaybe<AboutEnvironmentMutation>;
};

export type ServicesHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title_main?: InputMaybe<Scalars['String']['input']>;
  title_gradient?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesServicesPricesMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesServicesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  emoji?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  features_title?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  pricing_title?: InputMaybe<Scalars['String']['input']>;
  prices?: InputMaybe<Array<InputMaybe<ServicesServicesPricesMutation>>>;
};

export type ServicesCtaMutation = {
  title_main?: InputMaybe<Scalars['String']['input']>;
  title_gradient?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  phone_text?: InputMaybe<Scalars['String']['input']>;
  email_text?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesMutation = {
  hero?: InputMaybe<ServicesHeroMutation>;
  services?: InputMaybe<Array<InputMaybe<ServicesServicesMutation>>>;
  cta?: InputMaybe<ServicesCtaMutation>;
};

export type GroupsHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title_main?: InputMaybe<Scalars['String']['input']>;
  title_gradient?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type GroupsItemsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  emoji?: InputMaybe<Scalars['String']['input']>;
  age?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
  features_title?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  cta?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type GroupsMutation = {
  hero?: InputMaybe<GroupsHeroMutation>;
  items?: InputMaybe<Array<InputMaybe<GroupsItemsMutation>>>;
};

export type DocumentsHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title_main?: InputMaybe<Scalars['String']['input']>;
  title_gradient?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentsCategoriesMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DocumentsMutation = {
  hero?: InputMaybe<DocumentsHeroMutation>;
  categories?: InputMaybe<Array<InputMaybe<DocumentsCategoriesMutation>>>;
};

export type TeamMembersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  emoji?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  birthday?: InputMaybe<Scalars['String']['input']>;
  education?: InputMaybe<Scalars['String']['input']>;
  motto?: InputMaybe<Scalars['String']['input']>;
};

export type TeamMutation = {
  members?: InputMaybe<Array<InputMaybe<TeamMembersMutation>>>;
};

export type PromoMutation = {
  enabled?: InputMaybe<Scalars['Boolean']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  bannerText?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
  buttonLink?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
  expiresAt?: InputMaybe<Scalars['String']['input']>;
};

export type HomePartsFragment = { __typename: 'Home', hero?: { __typename: 'HomeHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null, cta_primary?: string | null, cta_secondary?: string | null } | null, advantages?: { __typename: 'HomeAdvantages', title_main?: string | null, title_gradient?: string | null, subtitle?: string | null, items?: Array<{ __typename: 'HomeAdvantagesItems', icon?: string | null, title?: string | null, desc?: string | null } | null> | null } | null };

export type PricesPartsFragment = { __typename: 'Prices', hero?: { __typename: 'PricesHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, plans?: Array<{ __typename: 'PricesPlans', id?: string | null, emoji?: string | null, name?: string | null, time?: string | null, price?: string | null, unit?: string | null, featured?: boolean | null, featured_badge?: string | null, features?: Array<{ __typename: 'PricesPlansFeatures', text?: string | null, included?: boolean | null } | null> | null } | null> | null, info?: { __typename: 'PricesInfo', title?: string | null, items?: Array<{ __typename: 'PricesInfoItems', icon?: string | null, title?: string | null, desc?: string | null } | null> | null } | null };

export type ContactsPartsFragment = { __typename: 'Contacts', hero?: { __typename: 'ContactsHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, contacts?: Array<{ __typename: 'ContactsContacts', icon?: string | null, title?: string | null, link?: string | null, link_text?: string | null, note?: string | null, multiline_text?: Array<string | null> | null } | null> | null, map?: { __typename: 'ContactsMap', url?: string | null, caption?: string | null } | null };

export type AboutPartsFragment = { __typename: 'About', hero?: { __typename: 'AboutHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, mission?: { __typename: 'AboutMission', title?: string | null, paragraphs?: Array<string | null> | null, visual_label?: string | null, visual_emoji?: string | null } | null, values?: { __typename: 'AboutValues', title?: string | null, subtitle?: string | null, items?: Array<{ __typename: 'AboutValuesItems', icon?: string | null, title?: string | null, desc?: string | null } | null> | null } | null, environment?: { __typename: 'AboutEnvironment', title?: string | null, subtitle?: string | null, features?: Array<string | null> | null } | null };

export type ServicesPartsFragment = { __typename: 'Services', hero?: { __typename: 'ServicesHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, services?: Array<{ __typename: 'ServicesServices', id?: string | null, emoji?: string | null, title?: string | null, description?: string | null, features_title?: string | null, features?: Array<string | null> | null, pricing_title?: string | null, prices?: Array<{ __typename: 'ServicesServicesPrices', name?: string | null, value?: string | null } | null> | null } | null> | null, cta?: { __typename: 'ServicesCta', title_main?: string | null, title_gradient?: string | null, subtitle?: string | null, phone_text?: string | null, email_text?: string | null } | null };

export type GroupsPartsFragment = { __typename: 'Groups', hero?: { __typename: 'GroupsHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, items?: Array<{ __typename: 'GroupsItems', id?: string | null, emoji?: string | null, age?: string | null, title?: string | null, desc?: string | null, features_title?: string | null, features?: Array<string | null> | null, cta?: string | null, link?: string | null } | null> | null };

export type DocumentsPartsFragment = { __typename: 'Documents', hero?: { __typename: 'DocumentsHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, categories?: Array<{ __typename: 'DocumentsCategories', icon?: string | null, title?: string | null, description?: string | null, items?: Array<string | null> | null } | null> | null };

export type TeamPartsFragment = { __typename: 'Team', members?: Array<{ __typename: 'TeamMembers', name?: string | null, role?: string | null, emoji?: string | null, photo?: string | null, birthday?: string | null, education?: string | null, motto?: string | null } | null> | null };

export type PromoPartsFragment = { __typename: 'Promo', enabled?: boolean | null, badge?: string | null, title?: string | null, text?: string | null, bannerText?: string | null, buttonText?: string | null, buttonLink?: string | null, color?: string | null, expiresAt?: string | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null, cta_primary?: string | null, cta_secondary?: string | null } | null, advantages?: { __typename: 'HomeAdvantages', title_main?: string | null, title_gradient?: string | null, subtitle?: string | null, items?: Array<{ __typename: 'HomeAdvantagesItems', icon?: string | null, title?: string | null, desc?: string | null } | null> | null } | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null, cta_primary?: string | null, cta_secondary?: string | null } | null, advantages?: { __typename: 'HomeAdvantages', title_main?: string | null, title_gradient?: string | null, subtitle?: string | null, items?: Array<{ __typename: 'HomeAdvantagesItems', icon?: string | null, title?: string | null, desc?: string | null } | null> | null } | null } | null } | null> | null } };

export type PricesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PricesQuery = { __typename?: 'Query', prices: { __typename: 'Prices', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'PricesHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, plans?: Array<{ __typename: 'PricesPlans', id?: string | null, emoji?: string | null, name?: string | null, time?: string | null, price?: string | null, unit?: string | null, featured?: boolean | null, featured_badge?: string | null, features?: Array<{ __typename: 'PricesPlansFeatures', text?: string | null, included?: boolean | null } | null> | null } | null> | null, info?: { __typename: 'PricesInfo', title?: string | null, items?: Array<{ __typename: 'PricesInfoItems', icon?: string | null, title?: string | null, desc?: string | null } | null> | null } | null } };

export type PricesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PricesFilter>;
}>;


export type PricesConnectionQuery = { __typename?: 'Query', pricesConnection: { __typename?: 'PricesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PricesConnectionEdges', cursor: string, node?: { __typename: 'Prices', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'PricesHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, plans?: Array<{ __typename: 'PricesPlans', id?: string | null, emoji?: string | null, name?: string | null, time?: string | null, price?: string | null, unit?: string | null, featured?: boolean | null, featured_badge?: string | null, features?: Array<{ __typename: 'PricesPlansFeatures', text?: string | null, included?: boolean | null } | null> | null } | null> | null, info?: { __typename: 'PricesInfo', title?: string | null, items?: Array<{ __typename: 'PricesInfoItems', icon?: string | null, title?: string | null, desc?: string | null } | null> | null } | null } | null } | null> | null } };

export type ContactsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactsQuery = { __typename?: 'Query', contacts: { __typename: 'Contacts', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ContactsHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, contacts?: Array<{ __typename: 'ContactsContacts', icon?: string | null, title?: string | null, link?: string | null, link_text?: string | null, note?: string | null, multiline_text?: Array<string | null> | null } | null> | null, map?: { __typename: 'ContactsMap', url?: string | null, caption?: string | null } | null } };

export type ContactsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactsFilter>;
}>;


export type ContactsConnectionQuery = { __typename?: 'Query', contactsConnection: { __typename?: 'ContactsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactsConnectionEdges', cursor: string, node?: { __typename: 'Contacts', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ContactsHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, contacts?: Array<{ __typename: 'ContactsContacts', icon?: string | null, title?: string | null, link?: string | null, link_text?: string | null, note?: string | null, multiline_text?: Array<string | null> | null } | null> | null, map?: { __typename: 'ContactsMap', url?: string | null, caption?: string | null } | null } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'AboutHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, mission?: { __typename: 'AboutMission', title?: string | null, paragraphs?: Array<string | null> | null, visual_label?: string | null, visual_emoji?: string | null } | null, values?: { __typename: 'AboutValues', title?: string | null, subtitle?: string | null, items?: Array<{ __typename: 'AboutValuesItems', icon?: string | null, title?: string | null, desc?: string | null } | null> | null } | null, environment?: { __typename: 'AboutEnvironment', title?: string | null, subtitle?: string | null, features?: Array<string | null> | null } | null } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'AboutHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, mission?: { __typename: 'AboutMission', title?: string | null, paragraphs?: Array<string | null> | null, visual_label?: string | null, visual_emoji?: string | null } | null, values?: { __typename: 'AboutValues', title?: string | null, subtitle?: string | null, items?: Array<{ __typename: 'AboutValuesItems', icon?: string | null, title?: string | null, desc?: string | null } | null> | null } | null, environment?: { __typename: 'AboutEnvironment', title?: string | null, subtitle?: string | null, features?: Array<string | null> | null } | null } | null } | null> | null } };

export type ServicesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServicesQuery = { __typename?: 'Query', services: { __typename: 'Services', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ServicesHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, services?: Array<{ __typename: 'ServicesServices', id?: string | null, emoji?: string | null, title?: string | null, description?: string | null, features_title?: string | null, features?: Array<string | null> | null, pricing_title?: string | null, prices?: Array<{ __typename: 'ServicesServicesPrices', name?: string | null, value?: string | null } | null> | null } | null> | null, cta?: { __typename: 'ServicesCta', title_main?: string | null, title_gradient?: string | null, subtitle?: string | null, phone_text?: string | null, email_text?: string | null } | null } };

export type ServicesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
}>;


export type ServicesConnectionQuery = { __typename?: 'Query', servicesConnection: { __typename?: 'ServicesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServicesConnectionEdges', cursor: string, node?: { __typename: 'Services', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ServicesHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, services?: Array<{ __typename: 'ServicesServices', id?: string | null, emoji?: string | null, title?: string | null, description?: string | null, features_title?: string | null, features?: Array<string | null> | null, pricing_title?: string | null, prices?: Array<{ __typename: 'ServicesServicesPrices', name?: string | null, value?: string | null } | null> | null } | null> | null, cta?: { __typename: 'ServicesCta', title_main?: string | null, title_gradient?: string | null, subtitle?: string | null, phone_text?: string | null, email_text?: string | null } | null } | null } | null> | null } };

export type GroupsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GroupsQuery = { __typename?: 'Query', groups: { __typename: 'Groups', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'GroupsHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, items?: Array<{ __typename: 'GroupsItems', id?: string | null, emoji?: string | null, age?: string | null, title?: string | null, desc?: string | null, features_title?: string | null, features?: Array<string | null> | null, cta?: string | null, link?: string | null } | null> | null } };

export type GroupsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GroupsFilter>;
}>;


export type GroupsConnectionQuery = { __typename?: 'Query', groupsConnection: { __typename?: 'GroupsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GroupsConnectionEdges', cursor: string, node?: { __typename: 'Groups', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'GroupsHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, items?: Array<{ __typename: 'GroupsItems', id?: string | null, emoji?: string | null, age?: string | null, title?: string | null, desc?: string | null, features_title?: string | null, features?: Array<string | null> | null, cta?: string | null, link?: string | null } | null> | null } | null } | null> | null } };

export type DocumentsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DocumentsQuery = { __typename?: 'Query', documents: { __typename: 'Documents', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'DocumentsHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, categories?: Array<{ __typename: 'DocumentsCategories', icon?: string | null, title?: string | null, description?: string | null, items?: Array<string | null> | null } | null> | null } };

export type DocumentsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentsFilter>;
}>;


export type DocumentsConnectionQuery = { __typename?: 'Query', documentsConnection: { __typename?: 'DocumentsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DocumentsConnectionEdges', cursor: string, node?: { __typename: 'Documents', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'DocumentsHero', badge?: string | null, title_main?: string | null, title_gradient?: string | null, subtitle?: string | null } | null, categories?: Array<{ __typename: 'DocumentsCategories', icon?: string | null, title?: string | null, description?: string | null, items?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type TeamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamQuery = { __typename?: 'Query', team: { __typename: 'Team', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'TeamMembers', name?: string | null, role?: string | null, emoji?: string | null, photo?: string | null, birthday?: string | null, education?: string | null, motto?: string | null } | null> | null } };

export type TeamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
}>;


export type TeamConnectionQuery = { __typename?: 'Query', teamConnection: { __typename?: 'TeamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamConnectionEdges', cursor: string, node?: { __typename: 'Team', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'TeamMembers', name?: string | null, role?: string | null, emoji?: string | null, photo?: string | null, birthday?: string | null, education?: string | null, motto?: string | null } | null> | null } | null } | null> | null } };

export type PromoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PromoQuery = { __typename?: 'Query', promo: { __typename: 'Promo', id: string, enabled?: boolean | null, badge?: string | null, title?: string | null, text?: string | null, bannerText?: string | null, buttonText?: string | null, buttonLink?: string | null, color?: string | null, expiresAt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PromoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PromoFilter>;
}>;


export type PromoConnectionQuery = { __typename?: 'Query', promoConnection: { __typename?: 'PromoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PromoConnectionEdges', cursor: string, node?: { __typename: 'Promo', id: string, enabled?: boolean | null, badge?: string | null, title?: string | null, text?: string | null, bannerText?: string | null, buttonText?: string | null, buttonLink?: string | null, color?: string | null, expiresAt?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  hero {
    __typename
    badge
    title_main
    title_gradient
    subtitle
    cta_primary
    cta_secondary
  }
  advantages {
    __typename
    title_main
    title_gradient
    subtitle
    items {
      __typename
      icon
      title
      desc
    }
  }
}
    `;
export const PricesPartsFragmentDoc = gql`
    fragment PricesParts on Prices {
  __typename
  hero {
    __typename
    badge
    title_main
    title_gradient
    subtitle
  }
  plans {
    __typename
    id
    emoji
    name
    time
    price
    unit
    featured
    featured_badge
    features {
      __typename
      text
      included
    }
  }
  info {
    __typename
    title
    items {
      __typename
      icon
      title
      desc
    }
  }
}
    `;
export const ContactsPartsFragmentDoc = gql`
    fragment ContactsParts on Contacts {
  __typename
  hero {
    __typename
    badge
    title_main
    title_gradient
    subtitle
  }
  contacts {
    __typename
    icon
    title
    link
    link_text
    note
    multiline_text
  }
  map {
    __typename
    url
    caption
  }
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  hero {
    __typename
    badge
    title_main
    title_gradient
    subtitle
  }
  mission {
    __typename
    title
    paragraphs
    visual_label
    visual_emoji
  }
  values {
    __typename
    title
    subtitle
    items {
      __typename
      icon
      title
      desc
    }
  }
  environment {
    __typename
    title
    subtitle
    features
  }
}
    `;
export const ServicesPartsFragmentDoc = gql`
    fragment ServicesParts on Services {
  __typename
  hero {
    __typename
    badge
    title_main
    title_gradient
    subtitle
  }
  services {
    __typename
    id
    emoji
    title
    description
    features_title
    features
    pricing_title
    prices {
      __typename
      name
      value
    }
  }
  cta {
    __typename
    title_main
    title_gradient
    subtitle
    phone_text
    email_text
  }
}
    `;
export const GroupsPartsFragmentDoc = gql`
    fragment GroupsParts on Groups {
  __typename
  hero {
    __typename
    badge
    title_main
    title_gradient
    subtitle
  }
  items {
    __typename
    id
    emoji
    age
    title
    desc
    features_title
    features
    cta
    link
  }
}
    `;
export const DocumentsPartsFragmentDoc = gql`
    fragment DocumentsParts on Documents {
  __typename
  hero {
    __typename
    badge
    title_main
    title_gradient
    subtitle
  }
  categories {
    __typename
    icon
    title
    description
    items
  }
}
    `;
export const TeamPartsFragmentDoc = gql`
    fragment TeamParts on Team {
  __typename
  members {
    __typename
    name
    role
    emoji
    photo
    birthday
    education
    motto
  }
}
    `;
export const PromoPartsFragmentDoc = gql`
    fragment PromoParts on Promo {
  __typename
  enabled
  badge
  title
  text
  bannerText
  buttonText
  buttonLink
  color
  expiresAt
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const PricesDocument = gql`
    query prices($relativePath: String!) {
  prices(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PricesParts
  }
}
    ${PricesPartsFragmentDoc}`;
export const PricesConnectionDocument = gql`
    query pricesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PricesFilter) {
  pricesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PricesParts
      }
    }
  }
}
    ${PricesPartsFragmentDoc}`;
export const ContactsDocument = gql`
    query contacts($relativePath: String!) {
  contacts(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactsParts
  }
}
    ${ContactsPartsFragmentDoc}`;
export const ContactsConnectionDocument = gql`
    query contactsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactsFilter) {
  contactsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactsParts
      }
    }
  }
}
    ${ContactsPartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const ServicesDocument = gql`
    query services($relativePath: String!) {
  services(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServicesParts
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ServicesConnectionDocument = gql`
    query servicesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServicesFilter) {
  servicesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServicesParts
      }
    }
  }
}
    ${ServicesPartsFragmentDoc}`;
export const GroupsDocument = gql`
    query groups($relativePath: String!) {
  groups(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GroupsParts
  }
}
    ${GroupsPartsFragmentDoc}`;
export const GroupsConnectionDocument = gql`
    query groupsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GroupsFilter) {
  groupsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GroupsParts
      }
    }
  }
}
    ${GroupsPartsFragmentDoc}`;
export const DocumentsDocument = gql`
    query documents($relativePath: String!) {
  documents(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DocumentsParts
  }
}
    ${DocumentsPartsFragmentDoc}`;
export const DocumentsConnectionDocument = gql`
    query documentsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DocumentsFilter) {
  documentsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DocumentsParts
      }
    }
  }
}
    ${DocumentsPartsFragmentDoc}`;
export const TeamDocument = gql`
    query team($relativePath: String!) {
  team(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamParts
  }
}
    ${TeamPartsFragmentDoc}`;
export const TeamConnectionDocument = gql`
    query teamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamFilter) {
  teamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamParts
      }
    }
  }
}
    ${TeamPartsFragmentDoc}`;
export const PromoDocument = gql`
    query promo($relativePath: String!) {
  promo(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PromoParts
  }
}
    ${PromoPartsFragmentDoc}`;
export const PromoConnectionDocument = gql`
    query promoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PromoFilter) {
  promoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PromoParts
      }
    }
  }
}
    ${PromoPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    prices(variables: PricesQueryVariables, options?: C): Promise<{data: PricesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricesQueryVariables, query: string}> {
        return requester<{data: PricesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricesQueryVariables, query: string}, PricesQueryVariables>(PricesDocument, variables, options);
      },
    pricesConnection(variables?: PricesConnectionQueryVariables, options?: C): Promise<{data: PricesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricesConnectionQueryVariables, query: string}> {
        return requester<{data: PricesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricesConnectionQueryVariables, query: string}, PricesConnectionQueryVariables>(PricesConnectionDocument, variables, options);
      },
    contacts(variables: ContactsQueryVariables, options?: C): Promise<{data: ContactsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactsQueryVariables, query: string}> {
        return requester<{data: ContactsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactsQueryVariables, query: string}, ContactsQueryVariables>(ContactsDocument, variables, options);
      },
    contactsConnection(variables?: ContactsConnectionQueryVariables, options?: C): Promise<{data: ContactsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactsConnectionQueryVariables, query: string}> {
        return requester<{data: ContactsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactsConnectionQueryVariables, query: string}, ContactsConnectionQueryVariables>(ContactsConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    services(variables: ServicesQueryVariables, options?: C): Promise<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}> {
        return requester<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}, ServicesQueryVariables>(ServicesDocument, variables, options);
      },
    servicesConnection(variables?: ServicesConnectionQueryVariables, options?: C): Promise<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}> {
        return requester<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}, ServicesConnectionQueryVariables>(ServicesConnectionDocument, variables, options);
      },
    groups(variables: GroupsQueryVariables, options?: C): Promise<{data: GroupsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GroupsQueryVariables, query: string}> {
        return requester<{data: GroupsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GroupsQueryVariables, query: string}, GroupsQueryVariables>(GroupsDocument, variables, options);
      },
    groupsConnection(variables?: GroupsConnectionQueryVariables, options?: C): Promise<{data: GroupsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GroupsConnectionQueryVariables, query: string}> {
        return requester<{data: GroupsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GroupsConnectionQueryVariables, query: string}, GroupsConnectionQueryVariables>(GroupsConnectionDocument, variables, options);
      },
    documents(variables: DocumentsQueryVariables, options?: C): Promise<{data: DocumentsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocumentsQueryVariables, query: string}> {
        return requester<{data: DocumentsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocumentsQueryVariables, query: string}, DocumentsQueryVariables>(DocumentsDocument, variables, options);
      },
    documentsConnection(variables?: DocumentsConnectionQueryVariables, options?: C): Promise<{data: DocumentsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocumentsConnectionQueryVariables, query: string}> {
        return requester<{data: DocumentsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DocumentsConnectionQueryVariables, query: string}, DocumentsConnectionQueryVariables>(DocumentsConnectionDocument, variables, options);
      },
    team(variables: TeamQueryVariables, options?: C): Promise<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}> {
        return requester<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}, TeamQueryVariables>(TeamDocument, variables, options);
      },
    teamConnection(variables?: TeamConnectionQueryVariables, options?: C): Promise<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}> {
        return requester<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}, TeamConnectionQueryVariables>(TeamConnectionDocument, variables, options);
      },
    promo(variables: PromoQueryVariables, options?: C): Promise<{data: PromoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PromoQueryVariables, query: string}> {
        return requester<{data: PromoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PromoQueryVariables, query: string}, PromoQueryVariables>(PromoDocument, variables, options);
      },
    promoConnection(variables?: PromoConnectionQueryVariables, options?: C): Promise<{data: PromoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PromoConnectionQueryVariables, query: string}> {
        return requester<{data: PromoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PromoConnectionQueryVariables, query: string}, PromoConnectionQueryVariables>(PromoConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  